apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  auth-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXM6NTQzMi9hdXRoX2Ri
  identity-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXM6NTQzMi9pZGVudGl0eV9kYg==
  promotion-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXM6NTQzMi9wcm9tb3Rpb25fZGI=
  gateway-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXM6NTQzMi9nYXRld2F5X2Ri
  form-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXM6NTQzMi9mb3JtX2Ri
  db-username: YWRtaW4=
  db-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  jwt-secret: Y2lyY2xlZ3VhcmQtand0LXNlY3JldC1rZXktcGxhY2Vob2xkZXI=
  ldap-url: bGRhcDovL2NpcmNsZWd1YXJkLW9wZW5sZGFwOjM4OQ==
  ldap-base-dn: ZGM9Y2lyY2xlZ3VhcmQsZGM9ZWR1
  ldap-manager-dn: Y249YWRtaW4sZGM9Y2lyY2xlZ3VhcmQsZGM9ZWR1
  ldap-manager-password: cGFzc3dvcmQ=
