apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  auth-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL2NpcmNsZWd1YXJk
  identity-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL2NpcmNsZWd1YXJk
  promotion-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL2NpcmNsZWd1YXJk
  gateway-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL2NpcmNsZWd1YXJk
  form-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vY2lyY2xlZ3VhcmQtcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL2NpcmNsZWd1YXJk
  db-username: YWRtaW4=
  db-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  jwt-secret: Y2lyY2xlZ3VhcmQtand0LXNlY3JldC1rZXktcGxhY2Vob2xkZXI=
  ldap-url: bGRhcDovL2NpcmNsZWd1YXJkLW9wZW5sZGFwOjM4OQ==
  ldap-base-dn: ZGM9Y2lyY2xlZ3VhcmQsZGM9ZWR1
  ldap-manager-dn: Y249YWRtaW4sZGM9Y2lyY2xlZ3VhcmQsZGM9ZWR1
  ldap-manager-password: cGFzc3dvcmQ=
