apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-service
  namespace: circleguard-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-service
  template:
    metadata:
      labels:
        app: form-service
    spec:
      containers:
        - name: form-service
          image: danieljpc1119/circleguard-form-service:staging
          ports:
            - containerPort: 8086
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://circleguard-postgres:5432/circleguard_form
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: circleguard-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: circleguard-kafka:9092
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: form-service
  namespace: circleguard-stage
spec:
  selector:
    app: form-service
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
