apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: circleguard-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: danieljpc1119/circleguard-gateway-service:staging
          ports:
            - containerPort: 8087
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/circleguard_gateway
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: circleguard-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: JWT_SECRET
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: QR_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: QR_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: circleguard-stage
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8087
      targetPort: 8087
  type: LoadBalancer
