apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: circleguard-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: danieljpc1119/circleguard-identity-service:staging
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/circleguard_identity
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: circleguard-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: JWT_SECRET
            - name: VAULT_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: VAULT_SECRET
            - name: VAULT_SALT
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: VAULT_SALT
            - name: VAULT_HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: circleguard-secret
                  key: VAULT_HASH_SALT
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: circleguard-stage
spec:
  selector:
    app: identity-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
