apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
  namespace: circleguard-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion-service
  template:
    metadata:
      labels:
        app: promotion-service
    spec:
      containers:
        - name: promotion-service
          image: danieljpc1119/circleguard-promotion-service:staging
          ports:
            - containerPort: 8088
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: promotion-db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: circleguard-kafka:9092
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: SPRING_NEO4J_URI
              value: bolt://circleguard-neo4j:7687
            - name: SPRING_NEO4J_AUTHENTICATION_USERNAME
              value: neo4j
            - name: SPRING_NEO4J_AUTHENTICATION_PASSWORD
              value: password
            - name: SPRING_DATA_REDIS_HOST
              value: circleguard-redis-master
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: promotion-service
  namespace: circleguard-stage
spec:
  selector:
    app: promotion-service
  ports:
    - port: 8088
      targetPort: 8088
  type: ClusterIP
